spring.datasource.url=jdbc:postgresql://localhost:5432/worknest_db
spring.datasource.username={DB_USER}
spring.datasource.password={DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
